baseURL = "https://r3s.nrw/"
languageCode = "en"
title = "Remote Rhein Ruhr"
theme = ["osm","ananke"]

DefaultContentLanguage = "de"
SectionPagesMenu = "main"
#Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.de]
    title = "Remote Rhein Ruhr"
    weight = 2

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "/images/favicon.png"
  site_logo = "/images/Rakete_w.png"
  description = "Remote Rhein Ruhr Stage http://r3s.nrw zum rC3"
  facebook = ""
  twitter = "https://twitter.com/RuhrStage"
  instagram = ""
  youtube = ""
  #github = "https://github.com/Neanderfunk/r3s-nrw"
  gitlab = ""
  linkedin = ""
  mastodon = "https://chaos.social/@r3s"
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/background.jpg"
  # recent_posts_number = 2

  [[menu.main]]
    name = "CfP"
    title = "CfP"
    weight = 1
    url = "/cfp"

    [[menu.main]]
    name = "FAQ"
    title = "faq"
    weight = 2
    url = "/faq"

    [[menu.main]]
    name = "Über uns"
    title = "Über uns"
    weight = 3
    url = "/about"

    [[menu.main]]
    name = "Anfahrt"
    title = "Anfahrt"
    weight = 4
    url = "/anfahrt"

    [[menu.main]]
    name = "Impressum"
    weight = 6
    url = "/impressum/"
