baseURL = "https://r3s.nrw/"
languageCode = "en"
title = "Remote Rhein Ruhr"
theme = ["osm","ananke"]

DefaultContentLanguage = "de"
SectionPagesMenu = "main"
enableRobotsTXT = true

[languages]
  [languages.de]
    title = "Remote Rhein Ruhr"
    weight = 2

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "/images/favicon.png"
  site_logo = "/images/Rakete_w.png"
  description = "Remote Rhein Ruhr Stage http://r3s.nrw zum rC3"
  twitter = "https://twitter.com/RuhrStage"
  #github = "https://github.com/Neanderfunk/r3s-nrw"
  mastodon = "https://chaos.social/@r3s"
  background_color_class = "bg-black"
  featured_image = "/images/background.jpg"

  [[languages.en.menu.main]]
    name = "CfP"
    title = "CfP"
    weight = 1
    url = "/cfp"

  [[languages.de.menu.main]]
    name = "CfP"
    title = "CfP"
    weight = 1
    url = "/cfp"

  [[languages.en.menu.main]]
    name = "FAQ"
    title = "faq"
    weight = 2
    url = "/faq"

  [[languages.de.menu.main]]
    name = "FAQ"
    title = "faq"
    weight = 2
    url = "/faq"

  [[languages.en.menu.main]]
    name = "About us"
    title = "About us"
    weight = 3
    url = "/about"

  [[languages.de.menu.main]]
    name = "Über uns"
    title = "Über uns"
    weight = 3
    url = "/about"

  [[languages.en.menu.main]]
    name = "Anfahrt"
    title = "Anfahrt"
    weight = 4
    url = "/anfahrt"

  [[languages.de.menu.main]]
    name = "Anfahrt"
    title = "Anfahrt"
    weight = 4
    url = "/anfahrt"

  [[languages.en.menu.main]]
    name = "Impressum"
    weight = 6
    url = "/impressum/"

  [[languages.de.menu.main]]
    name = "Impressum"
    weight = 6
    url = "/impressum/"
