baseURL = "https://r3s.nrw/"
languageCode = "en"
title = "Remote Rhein Ruhr Stage - r3s"
theme = ["osm","anpassungen","ananke"]

DefaultContentLanguage = "de"
SectionPagesMenu = "main"
enableRobotsTXT = false

[languages]

  [languages.en]
    title = "Remote Rhein Ruhr"
    weight = 1
  [languages.de]
    title = "Remote Rhein Ruhr"
    weight = 2

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "/images/favicon.png"
  site_logo = "/images/Rakete_w.png"
  description = "Remote Rhein Ruhr Stage http://r3s.nrw zum rC3"
  twitter = "https://twitter.com/RuhrStage"
  #github = "https://github.com/Neanderfunk/r3s-nrw"
  mastodon = "https://chaos.social/@r3s"
  background_color_class = "bg-black"
  featured_image = "/images/background.jpg"
  custom_css = ["/css/anpassungen.css"]

  [[languages.en.menu.main]]
    name = "CfP"
    title = "CfP"
    weight = 1
    url = "/en/cfp"

  [[languages.de.menu.main]]
    name = "CfP"
    title = "CfP"
    weight = 1
    url = "/cfp"

  [[languages.en.menu.main]]
    name = "FAQ"
    title = "faq"
    weight = 2
    url = "/en/faq"

  [[languages.de.menu.main]]
    name = "FAQ"
    title = "faq"
    weight = 2
    url = "/faq"

  [[languages.en.menu.main]]
    name = "About us"
    title = "About us"
    weight = 3
    url = "/en/about"

  [[languages.de.menu.main]]
    name = "Über uns"
    title = "Über uns"
    weight = 3
    url = "/about"

  [[languages.en.menu.main]]
    name = "directions"
    title = "directions"
    weight = 4
    url = "/en/anfahrt"

  [[languages.de.menu.main]]
    name = "Anfahrt"
    title = "Anfahrt"
    weight = 4
    url = "/anfahrt"

  [[languages.en.menu.main]]
    name = "unicorns"
    title = "unicorn"
    weight = 5
    url = "https://einhorn.r3s.nrw/"

  [[languages.de.menu.main]]
    name = "Einhörner"
    title = "Einhörner"
    weight = 5
    url = "https://einhorn.r3s.nrw/"

  [[languages.en.menu.footer]]
    name = "Impressum"
    weight = 6
    url = "/en/impressum/"

  [[languages.de.menu.footer]]
    name = "Impressum"
    weight = 6
    url = "/impressum/"
